import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Chat",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className="bg-blue-500 p-10">
      <h1>Hello React!</h1>
    </main>
  );
}
